# Generated by Django 5.0.2 on 2025-05-15 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estoque_preco_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquemovimentacao',
            name='nome_produto',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoquemovimentacao',
            name='id_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estoque'),
        ),
    ]
