# Generated by Django 5.0.2 on 2025-05-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_estoquemovimentacao_nome_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
