# Generated by Django 5.0.2 on 2025-05-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_venda_nome_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='id_produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estoque'),
        ),
    ]
