/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardGroup: typeof import('bootstrap-vue-next/components/BCard')['BCardGroup']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormInvalidFeedback']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BInputGroupText: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroupText']
    BLink: typeof import('bootstrap-vue-next/components/BLink')['BLink']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNav: typeof import('bootstrap-vue-next/components/BNav')['BNav']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    BToast: typeof import('bootstrap-vue-next/components/BToast')['BToast']
    BTooltip: typeof import('bootstrap-vue-next/components/BTooltip')['BTooltip']
    IMaterialSymbolsLogout: typeof import('~icons/material-symbols/logout')['default']
    IMdiAccountSearch: typeof import('~icons/mdi/account-search')['default']
    IMdiCheck: typeof import('~icons/mdi/check')['default']
    IMdiClockOutline: typeof import('~icons/mdi/clock-outline')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiEye: typeof import('~icons/mdi/eye')['default']
    IMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMynauiSidebar: typeof import('~icons/mynaui/sidebar')['default']
    ISvgSpinners3DotsScale: typeof import('~icons/svg-spinners/3-dots-scale')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    ModalDetails: typeof import('./src/components/ModalDetails.vue')['default']
    ModalNewOrder: typeof import('./src/components/ModalNewOrder.vue')['default']
    ModalNewProduct: typeof import('./src/components/ModalNewProduct.vue')['default']
    ModalRemoveItem: typeof import('./src/components/ModalRemoveItem.vue')['default']
    ModalSignup: typeof import('./src/components/ModalSignup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SubNav: typeof import('./src/components/SubNav.vue')['default']
    ToastMessages: typeof import('./src/components/ToastMessages.vue')['default']
    UpperNav: typeof import('./src/components/UpperNav.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
  }
}
