version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=h2ocontrol
      - POSTGRES_USER=h2ocontrol
      - POSTGRES_PASSWORD=h2ocontrol
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://h2ocontrol:h2ocontrol@db:5432/h2ocontrol
    depends_on:
      - db

volumes:
  postgres_data: 